'use client';

import { useEffect, useState } from 'react';
import { Download, FileSpreadsheet, FileText } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/api';

type Audit={id:string;name:string;status:string;createdAt:string};
export default function ReportsPage(){const [audits,setAudits]=useState<Audit[]>([]);useEffect(()=>{api<Audit[]>('/audits').then(setAudits).catch(()=>undefined)},[]);return <AppShell><div className="content"><div className="heading-row"><div><div className="eyebrow">Analitik</div><h1 className="page-title">Laporan</h1><p className="subtitle">Unduh data operasional dalam PDF atau Excel.</p></div></div><div className="stats-grid"><Report icon={<FileSpreadsheet size={20}/>} title="Inventaris aset" detail="Kode, serial, lokasi, status, kondisi, dan nilai aset." links={[['Excel','/api/v1/reports/assets.xlsx']]}/><Report icon={<FileText size={20}/>} title="Maintenance" detail="Keluhan, tindakan, teknisi, waktu, status, dan biaya perawatan." links={[['PDF','/api/v1/reports/maintenance.pdf'],['Excel','/api/v1/reports/maintenance.xlsx']]}/><div className="card" style={{gridColumn:'span 2'}}><div className="stat-icon"><FileText size={20}/></div><h2 style={{font:'800 16px var(--font-display)',margin:'16px 0 7px'}}>Hasil audit</h2><p className="subtitle">Pilih sesi untuk mengunduh klasifikasi ditemukan, tidak ditemukan, rusak, dan berbeda lokasi.</p><div style={{marginTop:14,maxHeight:240,overflow:'auto'}}>{audits.map(row=><div className="activity-item" key={row.id} style={{justifyContent:'space-between'}}><div><strong style={{fontSize:11}}>{row.name}</strong><span className="asset-code">{row.status} • {new Date(row.createdAt).toLocaleDateString('id-ID')}</span></div><div style={{display:'flex',gap:7}}><a className="button secondary" href={`/api/v1/reports/audits/${row.id}.pdf`}><Download size={13}/>PDF</a><a className="button secondary" href={`/api/v1/reports/audits/${row.id}.xlsx`}><Download size={13}/>Excel</a></div></div>)}{!audits.length&&<p className="subtitle">Belum ada sesi audit.</p>}</div></div></div></div></AppShell>}
function Report({icon,title,detail,links}:{icon:React.ReactNode;title:string;detail:string;links:string[][]}){return <div className="card"><div className="stat-icon">{icon}</div><h2 style={{font:'800 16px var(--font-display)',margin:'16px 0 7px'}}>{title}</h2><p className="subtitle" style={{minHeight:45}}>{detail}</p><div style={{display:'flex',gap:8,marginTop:16}}>{links.map(([label,href])=><a key={href} href={href} className="button secondary"><Download size={14}/>{label}</a>)}</div></div>}
