import { AppShell } from '@/components/app-shell';
import { ArrowUpRight, Boxes, CircleDollarSign, Clock3, MapPin, PackageCheck, Wrench } from 'lucide-react';

const bars=[['Laptop',88],['Monitor',61],['Printer',43],['Kendaraan',29],['Lainnya',49]];
export default function Dashboard(){return <AppShell><div className="content"><div className="heading-row"><div><div className="eyebrow">Selasa, 14 Juli 2026</div><h1 className="page-title">Selamat pagi, Admin.</h1><p className="subtitle">Berikut ringkasan kondisi aset perusahaan hari ini.</p></div><button className="button"><Boxes size={16}/><span>Tambah aset</span></button></div>
<section className="stats-grid"><Stat icon={<PackageCheck size={17}/>} label="Total aset" value="1.248" trend="+24 bulan ini"/><Stat icon={<CircleDollarSign size={17}/>} label="Nilai aset" value="Rp 4,8 M" trend="+3,2% dari bulan lalu"/><Stat icon={<Wrench size={17}/>} label="Maintenance" value="18" trend="7 perlu tindakan"/><Stat icon={<MapPin size={17}/>} label="Lokasi aktif" value="12" trend="6 departemen"/></section>
<section className="dashboard-grid"><div className="card"><div className="card-title"><span>Distribusi aset</span><button className="button secondary">Lihat laporan <ArrowUpRight size={13}/></button></div><div className="bar-chart">{bars.map(([name,height],i)=><div className="bar-wrap" key={name}><div className={`bar ${i===0?'highlight':''}`} style={{height:`${height}%`}}/><span>{name}</span></div>)}</div></div>
<div className="card"><div className="card-title"><span>Aktivitas terbaru</span><span style={{color:'#74817c',fontSize:10}}>Hari ini</span></div><Activity icon={<PackageCheck size={14}/>} title="Aset baru ditambahkan" detail="MacBook Pro 14 • AST-2026-041" time="8 menit"/><Activity icon={<Wrench size={14}/>} title="Maintenance diperbarui" detail="Printer LaserJet • Selesai" time="32 menit"/><Activity icon={<Clock3 size={14}/>} title="Aset dikembalikan" detail="ThinkPad X1 • Rina Amelia" time="1 jam"/></div></section>
<section style={{marginTop:16}} className="table-card"><div className="table-tools"><div className="card-title" style={{margin:0}}>Perlu perhatian</div><button className="button secondary">Lihat semua</button></div><table><thead><tr><th>Aset</th><th>Lokasi</th><th>Kondisi</th><th>Tenggat</th><th>Status</th></tr></thead><tbody><Row name="Printer LaserJet Pro" code="AST-2026-003" location="Gudang Utama" condition="Perlu perbaikan" due="Hari ini" badge="Maintenance" kind="warning"/><Row name="Proyektor Epson EB-X06" code="AST-2025-122" location="Ruang Meeting 3" condition="Baik" due="3 hari lagi" badge="Garansi" kind="danger"/></tbody></table></section>
</div></AppShell>}
function Stat({icon,label,value,trend}:{icon:React.ReactNode,label:string,value:string,trend:string}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className="stat-icon">{icon}</div></div><div className="stat-value">{value}</div><div className="trend">{trend}</div></div>}
function Activity({icon,title,detail,time}:{icon:React.ReactNode,title:string,detail:string,time:string}){return <div className="activity"><div className="activity-dot">{icon}</div><div><strong>{title}</strong><span>{detail}<br/>{time} lalu</span></div></div>}
function Row({name,code,location,condition,due,badge,kind}:{name:string,code:string,location:string,condition:string,due:string,badge:string,kind:string}){return <tr><td><span className="asset-name">{name}</span><span className="asset-code">{code}</span></td><td>{location}</td><td>{condition}</td><td>{due}</td><td><span className={`badge ${kind}`}>{badge}</span></td></tr>}
