'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { BrowserQRCodeReader, IScannerControls } from '@zxing/browser';
import { Camera, CloudOff, Keyboard, ScanLine } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/api';
import { markConflict, pendingScans, queueScan, removeScan } from '@/lib/offline-audit';

type Ref={id:string;name:string};
export default function ScanPage(){
  const [manual,setManual]=useState(''); const [active,setActive]=useState(false); const [message,setMessage]=useState(''); const [pending,setPending]=useState(0); const [conflicts,setConflicts]=useState(0); const [sessionId,setSession]=useState(''); const [condition,setCondition]=useState('GOOD'); const [location,setLocation]=useState(''); const [note,setNote]=useState(''); const [locations,setLocations]=useState<Ref[]>([]);
  const video=useRef<HTMLVideoElement>(null); const controls=useRef<IScannerControls|null>(null); const router=useRouter();
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('session')||'';setSession(id);api<Ref[]>('/masters/locations').then(setLocations).catch(()=>undefined);const reconnect=()=>{if(id)syncPending(id)};window.addEventListener('online',reconnect);if(id)syncPending(id);return()=>{controls.current?.stop();window.removeEventListener('online',reconnect)}},[]);
  async function refreshCounts(id:string){const rows=await pendingScans(id);setPending(rows.filter(row=>row.syncState==='pending').length);setConflicts(rows.filter(row=>row.syncState==='conflict').length);return rows}
  async function syncPending(id:string){const rows=(await refreshCounts(id)).filter(row=>row.syncState==='pending');if(!navigator.onLine||!rows.length)return;try{const operations=rows.map(({operationId,assetToken,scannedAt,condition,location,note})=>({operationId,assetToken,scannedAt,condition,location,note}));const response=await api<{results:{operationId:string;status:string}[]}>(`/audits/${id}/sync`,{method:'POST',body:JSON.stringify({operations})});for(const result of response.results){const row=rows.find(item=>item.operationId===result.operationId);if(result.status==='conflict'&&row)await markConflict(row);else await removeScan(result.operationId)}await refreshCounts(id);setMessage('Antrean offline berhasil disinkronkan.')}catch{setMessage('Antrean offline akan dicoba kembali saat koneksi stabil.')}}
  async function start(){setMessage('');try{setActive(true);const reader=new BrowserQRCodeReader();controls.current=await reader.decodeFromVideoDevice(undefined,video.current!,result=>{if(result){setManual(result.getText());controls.current?.stop();setActive(false)}})}catch(cause){setActive(false);setMessage(cause instanceof Error?`Kamera tidak dapat dibuka: ${cause.message}`:'Kamera tidak dapat dibuka.') }}
  async function submit(){if(!manual)return;const token=manual.split('/').filter(Boolean).pop()||manual;if(!sessionId){router.push(`/scan/${encodeURIComponent(token)}`);return}const operation={operationId:crypto.randomUUID(),sessionId,assetToken:token,scannedAt:new Date().toISOString(),condition,location:locations.find(row=>row.id===location)?.name,note:note||undefined};try{const {sessionId:_,...payload}=operation;const result=await api<{status:string}>(`/audits/${sessionId}/scan`,{method:'POST',body:JSON.stringify(payload)});if(result.status==='conflict')throw new Error('Scan ditolak karena sesi sudah selesai atau aset tidak ditemukan.');setMessage('Aset berhasil dicatat pada sesi audit.');setManual('');setNote('')}catch(cause){if(!navigator.onLine){await queueScan(operation);await refreshCounts(sessionId);setMessage('Perangkat offline. Scan disimpan dan akan disinkronkan otomatis.')}else setMessage(cause instanceof Error?cause.message:'Scan gagal diproses')}}
  return <AppShell><div className="content"><div className="scan-panel"><div className="eyebrow" style={{color:'#b7ccc5'}}>{sessionId?'Mode audit aktif':'Pemeriksaan aset'}</div><h1 className="page-title" style={{color:'white'}}>Pindai QR aset</h1><p style={{fontSize:12,color:'#b8cbc5'}}>Arahkan kamera ke QR Code atau masukkan kode aset.</p><div className="scanner">{active?<video ref={video} style={{width:'100%',height:310,objectFit:'cover',borderRadius:18}} muted playsInline/>:<div style={{textAlign:'center',color:'#9cb3ab'}}><Camera size={42} style={{margin:'auto auto 12px'}}/><div style={{fontSize:11}}>Izinkan kamera untuk mulai memindai</div></div>}</div><button className="button lime" onClick={start} style={{width:'100%',justifyContent:'center'}}><ScanLine size={16}/>Aktifkan kamera</button>
    <div style={{display:'flex',alignItems:'center',gap:12,margin:'20px 0',color:'#7f9a91',fontSize:10}}><div style={{height:1,background:'#31534c',flex:1}}/>DATA PEMINDAIAN<div style={{height:1,background:'#31534c',flex:1}}/></div>
    <div className="field"><label style={{color:'#b8cbc5'}}>Kode atau token QR</label><div className="search" style={{width:'100%',background:'#173e36',borderColor:'#31534c',color:'white'}}><Keyboard size={15}/><input style={{background:'transparent',color:'white'}} value={manual} onChange={event=>setManual(event.target.value)} placeholder="AST-2026-001"/></div></div>
    {sessionId&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="field"><label style={{color:'#b8cbc5'}}>Kondisi ditemukan</label><select value={condition} onChange={event=>setCondition(event.target.value)}><option value="GOOD">Baik</option><option value="DAMAGED">Rusak</option><option value="NEEDS_REPAIR">Perlu perbaikan</option><option value="UNKNOWN">Belum diketahui</option></select></div><div className="field"><label style={{color:'#b8cbc5'}}>Lokasi ditemukan</label><select value={location} onChange={event=>setLocation(event.target.value)}><option value="">Tidak dicatat</option>{locations.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="field" style={{gridColumn:'1 / -1'}}><label style={{color:'#b8cbc5'}}>Catatan</label><input value={note} onChange={event=>setNote(event.target.value)} placeholder="Catatan kondisi atau lokasi"/></div></div>}
    <button className="button lime" onClick={submit} style={{width:'100%',justifyContent:'center'}}>Simpan hasil scan</button>{message&&<p style={{fontSize:10,color:'#dff36b',marginTop:15}}>{message}</p>}<div style={{display:'flex',gap:7,alignItems:'center',marginTop:18,color:'#a7bdb5',fontSize:10}}><CloudOff size={14}/>{pending} menunggu sinkronisasi • {conflicts} konflik perlu ditinjau</div></div></div></AppShell>;
}
