'use client';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/api';
import { CheckCircle2, MapPin, Package, QrCode, UserRound } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';

type Asset = { id:string; code:string; name:string; serialNumber?:string; status:string; condition:string; location:{name:string}; category:{name:string}; department?:{name:string}; custodian?:{name:string} };
export default function ScannedAsset(){const {token}=useParams<{token:string}>();const [asset,setAsset]=useState<Asset|null>(null);const [error,setError]=useState('');useEffect(()=>{api<Asset>(`/assets/qr/${token}`).then(setAsset).catch(e=>setError(e instanceof Error?e.message:'Aset tidak ditemukan'))},[token]);return <AppShell><div className="content"><div className="heading-row"><div><div className="eyebrow">Hasil pemindaian QR</div><h1 className="page-title">{asset?.name||'Memeriksa aset...'}</h1><p className="subtitle">{asset?`${asset.code} • ${asset.serialNumber||'Tanpa serial'}`:'Menghubungkan ke data inventaris Assetra.'}</p></div><span className="badge"><QrCode size={13}/>QR terverifikasi</span></div>{error?<div className="card empty-illustration">{error}</div>:asset&&<div className="dashboard-grid"><div className="card"><div className="card-title">Informasi aset</div><Info icon={<Package size={16}/>} label="Kategori" value={asset.category.name}/><Info icon={<MapPin size={16}/>} label="Lokasi" value={asset.location.name}/><Info icon={<UserRound size={16}/>} label="Penanggung jawab" value={asset.custodian?.name||asset.department?.name||'Belum ditetapkan'}/><Info icon={<CheckCircle2 size={16}/>} label="Kondisi" value={asset.condition}/></div><div className="card"><div className="card-title">Status saat ini</div><div className="stat-value">{asset.status}</div><p className="subtitle">Perubahan melalui halaman ini akan tercatat pada riwayat immutable aset.</p><button className="button" style={{marginTop:22}}>Perbarui aset</button></div></div>}</div></AppShell>}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="activity"><div className="activity-dot">{icon}</div><div><strong>{label}</strong><span>{value}</span></div></div>}
