'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, CloudOff, Plus, ScanLine, Wifi } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/api';

type Ref={id:string;name:string};
type Audit={id:string;name:string;status:string;createdAt:string;startedAt?:string;location?:Ref;department?:Ref;_count:{results:number;events:number}};
export default function AuditPage(){
  const [audits,setAudits]=useState<Audit[]>([]); const [locations,setLocations]=useState<Ref[]>([]); const [departments,setDepartments]=useState<Ref[]>([]); const [name,setName]=useState(''); const [locationId,setLocation]=useState(''); const [departmentId,setDepartment]=useState(''); const [error,setError]=useState('');
  const load=()=>api<Audit[]>('/audits').then(setAudits).catch((cause)=>setError(cause instanceof Error?cause.message:'Audit gagal dimuat'));
  useEffect(()=>{load();Promise.all([api<Ref[]>('/masters/locations'),api<Ref[]>('/masters/departments')]).then(([l,d])=>{setLocations(l);setDepartments(d)}).catch(()=>undefined)},[]);
  async function create(event:FormEvent){event.preventDefault();setError('');try{await api('/audits',{method:'POST',body:JSON.stringify({name,...(locationId?{locationId}:{}),...(departmentId?{departmentId}:{})})});setName('');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Sesi gagal dibuat')}}
  async function action(id:string,type:'start'|'complete'){setError('');try{await api(`/audits/${id}/${type}`,{method:'POST'});await load()}catch(cause){setError(cause instanceof Error?cause.message:'Status audit gagal diperbarui')}}
  const active=audits.filter(row=>row.status==='ACTIVE');
  return <AppShell><div className="content"><div className="heading-row"><div><div className="eyebrow">Audit fisik</div><h1 className="page-title">Sesi audit</h1><p className="subtitle">Snapshot target berdasarkan lokasi/departemen dan scan tetap aman saat offline.</p></div></div>
    <form className="card" onSubmit={create}><div className="card-title">Buat sesi audit</div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr auto',gap:10,alignItems:'end'}}><div className="field" style={{margin:0}}><label>Nama sesi</label><input value={name} onChange={event=>setName(event.target.value)} required placeholder="Audit semester 2"/></div><Select label="Lokasi" value={locationId} set={setLocation} rows={locations}/><Select label="Departemen" value={departmentId} set={setDepartment} rows={departments}/><button className="button"><Plus size={16}/>Buat sesi</button></div>{error&&<p style={{color:'#b84b44',fontSize:11}}>{error}</p>}</form>
    <section className="stats-grid" style={{marginTop:16}}><Stat label="Sesi aktif" value={String(active.length)} icon={<Wifi size={17}/>}/><Stat label="Scan diterima" value={String(active.reduce((n,a)=>n+a._count.events,0))} icon={<CheckCircle2 size={17}/>}/><Stat label="Target audit" value={String(active.reduce((n,a)=>n+a._count.results,0))} icon={<ScanLine size={17}/>}/><Stat label="Mode offline" value="Aktif" icon={<CloudOff size={17}/>}/></section>
    <div className="table-card" style={{marginTop:16}}><div className="table-tools"><div className="card-title" style={{margin:0}}>Daftar sesi</div></div><table><thead><tr><th>Nama sesi</th><th>Cakupan</th><th>Hasil</th><th>Dibuat</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{audits.map(row=><tr key={row.id}><td><Link href={`/audit/${row.id}`} className="asset-name">{row.name}</Link><span className="asset-code">{row.id.slice(0,8).toUpperCase()}</span></td><td>{row.location?.name||'Semua lokasi'}<span className="asset-code">{row.department?.name||'Semua departemen'}</span></td><td><strong>{row._count.events} / {row._count.results}</strong></td><td>{new Date(row.createdAt).toLocaleDateString('id-ID')}</td><td><span className={`badge ${row.status==='DRAFT'?'warning':''}`}>{row.status}</span></td><td style={{display:'flex',gap:7}}>{row.status==='DRAFT'&&<button className="button secondary" onClick={()=>action(row.id,'start')}>Mulai</button>}{row.status==='ACTIVE'&&<><Link href={`/scan?session=${row.id}`} className="button lime"><ScanLine size={13}/>Scan</Link><button className="button secondary" onClick={()=>action(row.id,'complete')}>Selesaikan</button></>}<Link href={`/audit/${row.id}`} className="button secondary">Detail</Link></td></tr>)}</tbody></table>{!audits.length&&<div className="empty-illustration">Belum ada sesi audit.</div>}</div>
  </div></AppShell>;
}
function Select({label,value,set,rows}:{label:string;value:string;set:(value:string)=>void;rows:Ref[]}){return <div className="field" style={{margin:0}}><label>{label}</label><select value={value} onChange={event=>set(event.target.value)}><option value="">Semua</option>{rows.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></div>}
function Stat({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className="stat-icon">{icon}</div></div><div className="stat-value">{value}</div></div>}
